# Generated by Django 2.2.3 on 2019-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producter',
            field=models.CharField(max_length=200, null=True, verbose_name='产品负责人'),
        ),
    ]
